- id: ai-docfix
  name: AI DocFix
  description: Automatically generate docstrings for undocumented functions
  entry: python -m ai_docfix.__main__
  language: python
  types: [python]
  require_serial: true
  stages: [commit]
  pass_filenames: false
  additional_dependencies: ['google-generativeai']